Repository UMC-TripPiece/TripPiece-backend, pull requests merged in 2024-08, with the labels that each got.

#14 [feature] 회원가입 API 기능 구현
  build.gradle
  src/main/java/umc/TripPiece/TripPieceApplication.java
  src/main/java/umc/TripPiece/config/SecurityConfig.java
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/domain/enums/Gender.java
  src/main/java/umc/TripPiece/domain/enums/UserMethod.java
  src/main/java/umc/TripPiece/payload/ApiResponse.java
  src/main/java/umc/TripPiece/repository/UserRepository.java
  src/main/java/umc/TripPiece/service/UserService.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
  src/main/java/umc/TripPiece/web/dto/request/UserRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/UserResponseDto.java
  src/main/resources/application.yml
Labels: 🛠 feature

#16 [feature] 도시, 국가 검색 swagger test
  src/main/java/umc/TripPiece/converter/CityConverter.java
  src/main/java/umc/TripPiece/domain/TripPiece.java
  src/main/java/umc/TripPiece/service/CityService.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/CityController.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
Labels: 🛠 feature

#17 [feature] 여행 시작 구현
  src/main/java/umc/TripPiece/converter/TravelConverter.java
  src/main/java/umc/TripPiece/domain/Travel.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/request/TravelRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
Labels: 🛠 feature

#20 여행기 생성을 위한 controller, service, dto 구현
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
Labels: 🛠 feature

#21 [refactor] 디자인 수정 - 도시, 국가 검색 시 국기 이미지 반환
  src/main/java/umc/TripPiece/converter/CityConverter.java
  src/main/java/umc/TripPiece/domain/City.java
  src/main/java/umc/TripPiece/web/controller/CityController.java
  src/main/java/umc/TripPiece/web/dto/response/CityResponseDto.java
Labels: :recycle: refactor

#22 [feature] S3 사진/동영상 업로드 기능 추가, 다중 사진 업로드 기능 추가
  build.gradle
  src/main/java/umc/TripPiece/aws/s3/AmazonS3Manager.java
  src/main/java/umc/TripPiece/config/AmazonConfig.java
  src/main/java/umc/TripPiece/domain/Uuid.java
  src/main/java/umc/TripPiece/payload/code/status/ErrorStatus.java
  src/main/java/umc/TripPiece/payload/exception/ExceptionAdvice.java
  src/main/java/umc/TripPiece/payload/exception/GeneralException.java
  src/main/java/umc/TripPiece/payload/exception/handler/PictureHandler.java
  src/main/java/umc/TripPiece/payload/exception/handler/VideoHandler.java
  src/main/java/umc/TripPiece/repository/UuidRepository.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/resources/application.yml
Labels: 🛠 feature, ⚙ chore

#23 [feature] 여행 종료 기능 구현 및 에러 해결
  src/main/java/umc/TripPiece/converter/TravelConverter.java
  src/main/java/umc/TripPiece/repository/TripPieceRepository.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
Labels: :bug: fix, 🛠 feature

#24 [feature] 로그인 API 기능 구현
  build.gradle
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/domain/jwt/JWTProperties.java
  src/main/java/umc/TripPiece/domain/jwt/JWTUtil.java
  src/main/java/umc/TripPiece/domain/jwt/TokenProvider.java
  src/main/java/umc/TripPiece/payload/ApiResponse.java
  src/main/java/umc/TripPiece/service/UserService.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
  src/main/java/umc/TripPiece/web/dto/request/UserRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/UserResponseDto.java
  src/main/resources/application.yml
Labels: 🛠 feature

#25 [feature] 여행 시작 - 도시 썸네일 추가 기능 구현
  src/main/java/umc/TripPiece/domain/Travel.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/CityController.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/request/TravelRequestDto.java
Labels: 🛠 feature, :recycle: refactor

#27 [feature] 이모지, 글자수 제한 제약조건 구현
  src/main/java/umc/TripPiece/domain/Emoji.java
  src/main/java/umc/TripPiece/payload/code/status/ErrorStatus.java
  src/main/java/umc/TripPiece/payload/exception/handler/EmojiHandler.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/validation/annotation/CheckEmoji.java
  src/main/java/umc/TripPiece/validation/annotation/CheckEmojiNum.java
  src/main/java/umc/TripPiece/validation/annotation/TextLength100.java
  src/main/java/umc/TripPiece/validation/annotation/TextLength30.java
  src/main/java/umc/TripPiece/validation/validator/CheckEmojiNumValidator.java
  src/main/java/umc/TripPiece/validation/validator/CheckEmojiValidator.java
  src/main/java/umc/TripPiece/validation/validator/TextLength100Validator.java
  src/main/java/umc/TripPiece/validation/validator/TextLength30Validator.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
Labels: 🛠 feature, :recycle: refactor

#29 [refactor] 여행 날짜 입력 형식 변경 및 제목 글자수 제한
  src/main/java/umc/TripPiece/converter/TravelConverter.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/request/TravelRequestDto.java
Labels: :recycle: refactor

#30 [refactor] 여행 종료시 반환 날짜 형식 변경
  src/main/java/umc/TripPiece/converter/TravelConverter.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
Labels: :recycle: refactor

#34 [feature] 토큰 재발급 및 로그아웃
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/domain/jwt/JWTUtil.java
  src/main/java/umc/TripPiece/repository/UserRepository.java
  src/main/java/umc/TripPiece/service/UserService.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
  src/main/java/umc/TripPiece/web/dto/request/UserRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/UserResponseDto.java
  src/main/resources/application.yml
Labels: 🛠 feature

#39 [feature] 여행 생성 기능 header에 userId token 받기
  src/main/java/umc/TripPiece/domain/Travel.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
Labels: 🛠 feature

#40 [feature] 생성된 여행기 클릭 시 상세 화면에 해당하는 데이터 보여주기
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
Labels: 🛠 feature

#42 [feature] 생성된 여행기 반환시 header에 userId token 받기
  src/main/java/umc/TripPiece/repository/TravelRepository.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
Labels: 🛠 feature

#41 [feature] 지난 여행 조각 받아오기 구현(전체/사진/영상/메모) + token 적용
  src/main/java/umc/TripPiece/converter/TravelConverter.java
  src/main/java/umc/TripPiece/converter/TripPieceConverter.java
  src/main/java/umc/TripPiece/domain/TripPiece.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/repository/TravelRepository.java
  src/main/java/umc/TripPiece/repository/TripPieceRepository.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/service/TripPieceService.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/controller/TripPieceController.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
  src/main/java/umc/TripPiece/web/dto/response/TripPieceResponseDto.java
  src/main/resources/application.yml
Labels: 🛠 feature, :recycle: refactor

#44 [feature] 단일 여행 조각 조회 구현
  src/main/java/umc/TripPiece/converter/TripPieceConverter.java
  src/main/java/umc/TripPiece/service/TripPieceService.java
  src/main/java/umc/TripPiece/web/controller/TripPieceController.java
  src/main/java/umc/TripPiece/web/dto/response/TripPieceResponseDto.java
Labels: 🛠 feature

#45 [refactor] Country 테이블에 국가코드(code) 컬럼 추가
  src/main/java/umc/TripPiece/domain/Country.java
Labels: :recycle: refactor

#46 [feature] 카카오 로그인 및 회원가입
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/repository/UserRepository.java
  src/main/java/umc/TripPiece/service/UserService.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/web/controller/KakaoController.java
  src/main/java/umc/TripPiece/web/dto/request/UserRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/UserResponseDto.java
Labels: 🛠 feature

#48 [feature] 회원가입 시 프로필 사진 설정/프로필 변경 기능 구현
  src/main/java/umc/TripPiece/aws/s3/AmazonS3Manager.java
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/service/UserService.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/web/controller/KakaoController.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
  src/main/java/umc/TripPiece/web/dto/request/UserRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/UserResponseDto.java
Labels: 🛠 feature

#49 [fix] 카카오 유저 userId값 추가
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/web/dto/response/UserResponseDto.java
Labels: :bug: fix

#50 [feature] Map 관련 기능 구현
  src/main/java/umc/TripPiece/converter/MapConverter.java
  src/main/java/umc/TripPiece/domain/Map.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/domain/enums/Color.java
  src/main/java/umc/TripPiece/repository/CityRepository.java
  src/main/java/umc/TripPiece/repository/MapRepository.java
  src/main/java/umc/TripPiece/service/MapService.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/validation/annotation/CheckEmoji.java
  src/main/java/umc/TripPiece/validation/annotation/CheckEmojiNum.java
  src/main/java/umc/TripPiece/validation/annotation/TextLength100.java
  src/main/java/umc/TripPiece/validation/annotation/TextLength30.java
  src/main/java/umc/TripPiece/validation/validator/CheckEmojiNumValidator.java
  src/main/java/umc/TripPiece/validation/validator/CheckEmojiValidator.java
  src/main/java/umc/TripPiece/validation/validator/TextLength100Validator.java
  src/main/java/umc/TripPiece/validation/validator/TextLength30Validator.java
  src/main/java/umc/TripPiece/web/controller/MapController.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/request/MapRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/ApiResponse.java
  src/main/java/umc/TripPiece/web/dto/response/MapResponseDto.java
  src/main/java/umc/TripPiece/web/dto/response/MapStatsResponseDto.java
Labels: 🛠 feature

#51 [feature] 프로필 조회 기능 구현
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/City.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/service/UserService.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
  src/main/java/umc/TripPiece/web/dto/response/UserResponseDto.java
Labels: 🛠 feature

#52 [fix] color post error fix
  src/main/java/umc/TripPiece/domain/enums/Color.java
Labels: :bug: fix

#53 [feature] 400 에러 처리
  src/main/java/umc/TripPiece/service/CityService.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/CityController.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/request/CityRequestDto.java
Labels: 🛠 feature

#54 [feature] 구글 맵 지도 마커 반환 API 구현 + 예외 처리 추가
  src/main/java/umc/TripPiece/converter/MapConverter.java
  src/main/java/umc/TripPiece/repository/MapRepository.java
  src/main/java/umc/TripPiece/repository/TripPieceRepository.java
  src/main/java/umc/TripPiece/service/MapService.java
  src/main/java/umc/TripPiece/web/controller/MapController.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/controller/TripPieceController.java
  src/main/java/umc/TripPiece/web/dto/response/MapResponseDto.java
Labels: 🛠 feature, :recycle: refactor

#58 [refactor] 카카오 회원가입 name request 제거
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/web/dto/request/UserRequestDto.java
Labels: :bug: fix, :recycle: refactor

#59 [refactor] ONGOING 여행 정보 반환 API response 수정
  src/main/java/umc/TripPiece/converter/TravelConverter.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
Labels: :recycle: refactor

#60 [refactor] 현재 진행중인 여행기 response 수정
  src/main/java/umc/TripPiece/converter/TravelConverter.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
Labels: :recycle: refactor

#62 [refactor] 여행 조각 생성 시 글자 수 제한 수정
  src/main/java/umc/TripPiece/web/controller/TravelController.java
Labels: :recycle: refactor

#64 chore : Remove sensitive information
  .DS_Store
  src/main/java/umc/TripPiece/converter/TravelConverter.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
Labels: 🛠 feature
