Repository UMC-TripPiece/TripPiece-backend, pull requests merged in 2024-12, with the labels that each got.

#86 [refactor] 여행기 조각 정렬 및 프로필 수정 API 리팩토링
  src/main/java/umc/TripPiece/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/TripPiece/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/TripPiece/apiPayload/exception/handler/BadRequestHandler.java
  src/main/java/umc/TripPiece/apiPayload/exception/handler/NotFoundHandler.java
  src/main/java/umc/TripPiece/apiPayload/exception/handler/UserHandler.java
  src/main/java/umc/TripPiece/service/TripPieceService.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/web/controller/TripPieceController.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
Labels: 🛠 feature, :recycle: refactor

#87 [feature] 여행기 퍼즐 사진 수정
  src/main/java/umc/TripPiece/converter/TravelConverter.java
  src/main/java/umc/TripPiece/domain/Picture.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
Labels: 🛠 feature

#88 [refactor] 현재 진행중인 여행기 반환 response에 id 추가
  src/main/java/umc/TripPiece/converter/TravelConverter.java
  src/main/java/umc/TripPiece/web/dto/response/TravelResponseDto.java
Labels: :recycle: refactor

#89 [feature] 요즘 떠오르는 도시 api 구현
  .DS_Store
  src/main/java/umc/TripPiece/converter/ExploreConverter.java
  src/main/java/umc/TripPiece/domain/City.java
  src/main/java/umc/TripPiece/repository/CityRepository.java
  src/main/java/umc/TripPiece/service/CityService.java
  src/main/java/umc/TripPiece/service/ExploreService.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/web/controller/ExploreController.java
  src/main/java/umc/TripPiece/web/dto/response/ExploreResponseDto.java
Labels: 🛠 feature

#90 [feature] 도시 국가 검색 시 최신순, 오래된순 필터링 기능 추가
  src/main/java/umc/TripPiece/repository/TravelRepository.java
  src/main/java/umc/TripPiece/service/ExploreService.java
  src/main/java/umc/TripPiece/web/controller/ExploreController.java
Labels: 🛠 feature
