Repository UMC-TripPiece/TripPiece-backend, pull requests merged in 2025-02, with the labels that each got.

#130 [fix] 최신 수정 데이터 정렬 오류 해결
  src/main/java/umc/TripPiece/repository/MapRepository.java
  src/main/java/umc/TripPiece/service/MapService.java
Labels: :bug: fix

#132 [chore] docker 연동
  .github/workflows/dev_deploy.yml
  Dockerfile
Labels: ⚙ chore

#138 [fix] 국가 검색 시 해당 국가 도시 결과 반환
  src/main/java/umc/TripPiece/repository/CityRepository.java
  src/main/java/umc/TripPiece/service/MapService.java
  src/main/java/umc/TripPiece/web/controller/MapController.java
Labels: :bug: fix

#140 [fix] 여행기 반환 dayCount 로직 수정
  src/main/java/umc/TripPiece/service/TravelService.java
Labels: :bug: fix

#145 [fix] MemoDto 수정
  src/main/java/umc/TripPiece/web/dto/request/TravelRequestDto.java
Labels: :bug: fix

#146 [feature] User Entity gpsConsent 필드 삭제 #143
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/User.java
Labels: :bug: fix

#147 [feature] 회원가입 시 프로필 설정 선택 허용
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/validation/validator/FutureDateValidator.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
  src/main/java/umc/TripPiece/web/dto/request/UserRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/UserResponseDto.java
Labels: 🛠 feature
