Repository UMC-TripPiece/TripPiece-backend, pull requests merged in 2025-01, with the labels that each got.

#94 [feature] userid 식별
  .DS_Store
  src/main/java/umc/TripPiece/domain/Travel.java
  src/main/java/umc/TripPiece/domain/User.java
  src/main/java/umc/TripPiece/service/UserService.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
  src/main/java/umc/TripPiece/web/dto/response/UserResponseDto.java
Labels: 🛠 feature

#95 [refactor] 탐색 API ErrorStatus 설정
  src/main/java/umc/TripPiece/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/TripPiece/service/ExploreService.java
  src/main/java/umc/TripPiece/web/controller/ExploreController.java
Labels: :recycle: refactor

#97 [refactor] 여행기, 지도 검색 관련 api 코드 리팩토링 및 중복 코드 개선, 커스텀 어노테이션 생성
  build.gradle
  src/main/java/umc/TripPiece/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/TripPiece/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/TripPiece/apiPayload/exception/GeneralException.java
  src/main/java/umc/TripPiece/config/ValidatorConfig.java
  src/main/java/umc/TripPiece/converter/CityConverter.java
  src/main/java/umc/TripPiece/converter/MapConverter.java
  src/main/java/umc/TripPiece/repository/CityRepository.java
  src/main/java/umc/TripPiece/repository/CountryRepository.java
  src/main/java/umc/TripPiece/service/CityService.java
  src/main/java/umc/TripPiece/service/ExploreService.java
  src/main/java/umc/TripPiece/service/MapService.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/validation/annotation/ExistEntity.java
  src/main/java/umc/TripPiece/validation/annotation/ValidateToken.java
  src/main/java/umc/TripPiece/validation/aspect/TokenValidationAspect.java
  src/main/java/umc/TripPiece/validation/aspect/UserContext.java
  src/main/java/umc/TripPiece/validation/validator/EntityExistValidator.java
  src/main/java/umc/TripPiece/web/controller/CityController.java
  src/main/java/umc/TripPiece/web/controller/MapController.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/request/CityRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/CityResponseDto.java
  src/main/java/umc/TripPiece/web/dto/response/MapResponseDto.java
Labels: :recycle: refactor

#98 [feature] 소셜 로그인 (애플 로그인 기능 추가) 및 에러 코드 리팩토링
  src/main/java/umc/TripPiece/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/TripPiece/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/TripPiece/apiPayload/exception/GeneralException.java
  src/main/java/umc/TripPiece/apiPayload/exception/handler/NotFoundHandler.java
  src/main/java/umc/TripPiece/converter/UserConverter.java
  src/main/java/umc/TripPiece/domain/enums/UserMethod.java
  src/main/java/umc/TripPiece/repository/UserRepository.java
  src/main/java/umc/TripPiece/service/EmailService.java
  src/main/java/umc/TripPiece/service/UserService.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/validation/RegexConstants.java
  src/main/java/umc/TripPiece/validation/annotation/ValidBirth.java
  src/main/java/umc/TripPiece/validation/validator/FutureDateValidator.java
  src/main/java/umc/TripPiece/web/controller/EmailController.java
  src/main/java/umc/TripPiece/web/controller/KakaoController.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
  src/main/java/umc/TripPiece/web/dto/request/EmailRequestDto.java
  src/main/java/umc/TripPiece/web/dto/request/UserRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/UserResponseDto.java
Labels: 🛠 feature, :recycle: refactor

#102 [feature] 프로필 조회 시 userId 반환
  src/main/java/umc/TripPiece/converter/UserConverter.java
Labels: 🛠 feature

#103 [feature] 앱 사용 촉구 푸시 알림 구현
  .github/workflows/dev_deploy.yml
  .gitignore
  build.gradle
  src/main/java/umc/TripPiece/config/ScheduledConfig.java
  src/main/java/umc/TripPiece/domain/enums/RequestPushMessage.java
  src/main/java/umc/TripPiece/domain/firebase/NotificationScheduler.java
  src/main/resources/application.yml
Labels: 🛠 feature

#105 [refactor] 토큰 검증 전역 처리
  src/main/java/umc/TripPiece/config/WebConfig.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/validation/annotation/ExistCity.java
  src/main/java/umc/TripPiece/validation/annotation/ExistMap.java
  src/main/java/umc/TripPiece/validation/annotation/ExistUser.java
  src/main/java/umc/TripPiece/validation/interceptor/TokenValidationInterceptor.java
  src/main/java/umc/TripPiece/validation/validator/CityExistValidator.java
  src/main/java/umc/TripPiece/validation/validator/MapExistValidator.java
  src/main/java/umc/TripPiece/validation/validator/UserExistValidator.java
  src/main/java/umc/TripPiece/web/controller/MapController.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/request/MapRequestDto.java
Labels: 🛠 feature, :recycle: refactor

#107 [refactor] spring security 적용
  src/main/java/umc/TripPiece/config/SecurityConfig.java
  src/main/java/umc/TripPiece/config/WebConfig.java
  src/main/java/umc/TripPiece/security/JwtExceptionFilter.java
  src/main/java/umc/TripPiece/security/JwtTokenFilter.java
  src/main/java/umc/TripPiece/security/SecurityUtils.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/validation/aspect/TokenValidationAspect.java
  src/main/java/umc/TripPiece/validation/aspect/UserContext.java
  src/main/java/umc/TripPiece/validation/interceptor/TokenValidationInterceptor.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#108 feat: Add HEX color handling and map-related updates
  src/main/java/umc/TripPiece/converter/MapConverter.java
  src/main/java/umc/TripPiece/domain/Map.java
  src/main/java/umc/TripPiece/domain/enums/Color.java
  src/main/java/umc/TripPiece/service/MapService.java
  src/main/java/umc/TripPiece/web/dto/request/MapRequestDto.java
  src/main/java/umc/TripPiece/web/dto/response/MapResponseDto.java
Labels: 🛠 feature

#113 [feature] 도시, 국가명 혼합 검색 기능 추가
  src/main/java/umc/TripPiece/repository/CityRepository.java
  src/main/java/umc/TripPiece/repository/CountryRepository.java
  src/main/java/umc/TripPiece/service/ExploreService.java
  src/main/java/umc/TripPiece/web/controller/ExploreController.java
Labels: 🛠 feature

#116 이미지 및 동영상 확장자 예외 처리/여행 상태 스케줄러 구현/코드 리팩토링
  src/main/java/umc/TripPiece/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/TripPiece/aws/s3/AmazonS3Manager.java
  src/main/java/umc/TripPiece/domain/jwt/TokenProvider.java
  src/main/java/umc/TripPiece/domain/scheduler/TravelStatusScheduler.java
  src/main/java/umc/TripPiece/repository/TravelRepository.java
  src/main/java/umc/TripPiece/security/JwtExceptionFilter.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/service/TripPieceService.java
  src/main/java/umc/TripPiece/service/UserService.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/controller/TripPieceController.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
Labels: 🛠 feature, :recycle: refactor

#118 [feature] 회원 API 관련 수정사항 반영
  src/main/java/umc/TripPiece/config/SecurityConfig.java
  src/main/java/umc/TripPiece/service/UserServiceImpl.java
  src/main/java/umc/TripPiece/web/controller/UserController.java
  src/main/java/umc/TripPiece/web/dto/request/UserRequestDto.java
Labels: 🛠 feature

#124 [feature] 이메일 인증번호 발송 시 중복 검사 추가
  src/main/java/umc/TripPiece/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/TripPiece/repository/UserRepository.java
  src/main/java/umc/TripPiece/web/controller/EmailController.java
Labels: 🛠 feature

#125 [refactor] S3 파일 업로드 용량 / 이모지 및 맵 Request 수정
  src/main/java/umc/TripPiece/converter/MapConverter.java
  src/main/java/umc/TripPiece/service/MapService.java
  src/main/java/umc/TripPiece/service/TravelService.java
  src/main/java/umc/TripPiece/service/TripPieceService.java
  src/main/java/umc/TripPiece/web/controller/MapController.java
  src/main/java/umc/TripPiece/web/controller/TravelController.java
  src/main/java/umc/TripPiece/web/dto/request/MapRequestDto.java
  src/main/java/umc/TripPiece/web/dto/request/TravelRequestDto.java
  src/main/resources/application.yml
Labels: :recycle: refactor, ⚙ chore

#126 [feature] 이메일 인증번호 발송 API 중복 이메일일 시 응답 200 반환
  src/main/java/umc/TripPiece/apiPayload/ApiResponse.java
  src/main/java/umc/TripPiece/web/controller/EmailController.java
Labels: 🛠 feature
